[package]
name = "ads_forwarder_rs"
version = "1.0.3"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Forwarder for Beckhoff TCP/UDP connections."

[[bin]]
name = "ads_forwarder_rs"
path = "src/main.rs"

[dependencies]
crossbeam-channel = "0.3"
byteorder = "1.2"
structopt = "0.2"
signalbool = "0.2"
itertools = "0.7"
mlzutil = { version = "0.1", features = ["interfaces"] }
mlzlog = "0.4"
log = "0.4"
