[package]
name = "ads_forwarder_rs"
version = "1.0.2"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Forwarder for Beckhoff TCP/UDP connections."

[[bin]]
name = "ads_forwarder_rs"
path = "src/main.rs"

[dependencies]
crossbeam-channel = { git = "https://github.com/crossbeam-rs/crossbeam-channel" }
byteorder = "*"
structopt = "*"
interfaces = "*"
signalbool = "*"
itertools = "*"
mlzutil = { version = "*", features = ["interfaces"] }
mlzlog = "*"
log = "*"
