[package]
name = "ads_forwarder_rs"
version = "1.0.11"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Forwarder for Beckhoff TCP/UDP connections."
edition = "2018"

[[bin]]
name = "ads_forwarder_rs"
path = "src/main.rs"

[dependencies]
crossbeam-channel = "0.4.0"
byteorder = "1.3.1"
structopt = "0.3.0"
signalbool = "0.2.2"
itertools = "0.8.0"
mlzutil = "0.2.0"
mlzlog = "0.5.1"
anyhow = "1.0.20"
log = "0.4.6"
