[package]
name = "ads_forwarder_rs"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Forwarder for Beckhoff TCP/UDP connections."

[[bin]]
name = "ads_forwarder_rs"
path = "src/main.rs"

[dependencies]
crossbeam-channel = "*"
byteorder = "*"
structopt = "*"
structopt-derive = "*"
interfaces = "*"
itertools = "*"
mlzlog = "*"
log = "*"
