[package]
name = "ads_forwarder_rs"
version = "1.0.14"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Forwarder for Beckhoff TCP/UDP connections."
edition = "2018"

[[bin]]
name = "ads_forwarder_rs"
path = "src/main.rs"

[dependencies]
crossbeam-channel = "0.5.0"
byteorder = "1.3.1"
structopt = "0.3.0"
itertools = "0.10.0"
mlzutil = "0.2.1"
mlzlog = "0.7.0"
anyhow = "1.0.20"
log = "0.4.6"
signalbool = "0.2.3"
dns-lookup = "=1.0.5"  # for 1.41.1 compat
