[package]
name = "ads_forwarder_rs"
version = "0.1.0"
authors = ["Georg Brandl <g.brandl@fz-juelich.de>"]
description = "Forwarder for Beckhoff TCP/UDP connections."

[[bin]]
name = "ads_forwarder_rs"
path = "src/main.rs"

[dependencies]
parking_lot = "*"
crossbeam-channel = "*"
byteorder = "*"
structopt = "*"
structopt-derive = "*"
# use master until 32bit fix is released
interfaces = { git = "https://github.com/andrew-d/interfaces-rs" }
itertools = "*"
structure = "*"
mlzlog = "*"
log = "*"
net2 = "*"
